sonar.projectName=FastTimes
sonar.sourceEncoding=UTF-8
sonar.sources=app/src/main,app/src/foss,app/src/debug
sonar.tests=app/src/test,app/src/androidTest
sonar.java.binaries=app/build/intermediates/classes/fossDebug/transformFossDebugClassesWithAsm/dirs
sonar.java.test.binaries=app/build/intermediates/classes/fossDebugUnitTest/transformFossDebugUnitTestClassesWithAsm/dirs
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoFossDebugReport/jacocoFossDebugReport.xml
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
